### ISSUE TITLE
de-conflict duplicate column names

### ISSUE THREAD

**Issue by dcooley** [dcooley/sfheaders#50]
```r


library(sfheaders)

df <- data.frame(
  x1 = 1:5
  , y = 1:5
  , x = 1:5
)

sf <- sfheaders::sf_point(df, x = "x1", y = "y", keep = T)

sfheaders::sf_to_df(sf, fill = T)
#   x sfg_id point_id x y
# 1 1      1        1 1 1
# 2 2      2        2 2 2
# 3 3      3        3 3 3
# 4 4      4        4 4 4
# 5 5      5        5 5 5

```

### TODO

Decide betwen 

- [ ] replacing data column `x` with `x..1`
- [x] replacing sfg column `x` with `x..1`
- [x] have an attribute (sfc_columns) on the data.frame giving the `x`, `y`, `z`, `m` column names
