### ISSUE TITLE
no control to get XYM geometry

### ISSUE THREAD

**Issue by mdsumner** [dcooley/sfheaders#64]
This gives XYZ but should be XYM, perhaps an oversight? (since XYM is pretty obscure)  

```R
df <- data.frame(
  ml_id = c(1,1,1,1,1,1,1,1,2,2,2,2,2)
  , l_id = c(1,1,1,2,2,3,3,3,1,1,1,2,2)
  , x = rnorm(13)
  , y = rnorm(13)
  , z = rnorm(13)
  , m = rnorm(13)
)

sf_multilinestring(df, x = "x", y = "y", m = "m")
Simple feature collection with 1 feature and 1 field
geometry type:  MULTILINESTRING
dimension:      XYZ
bbox:           xmin: -1.771925 ymin: -1.616244 xmax: 2.101231 ymax: 2.096727
epsg (SRID):    NA
proj4string:    NA
  id                       geometry
1  1 MULTILINESTRING Z ((-1.7719...
```

Same with other funs: 

```R
sf_point(obj = df, x = "x", y = "y", m = "m")
sf_multipoint(obj = df, x = "x", y = "y", m = "m")
sf_multilinestring( obj = df, x = "x", y = "y", m = "m")
sf_linestring( obj = df, x = "x", y = "y", m = "m")
sf_polygon( obj = df, x = "x", y = "y", m = "m")
sf_multipolygon( obj = df, x = "x", y = "y", m = "m")
```

In sf it is: 

```R
library(sf)
st_multilinestring(list(cbind(0, 0, 0)), dim = "XYM")
MULTILINESTRING M ((0 0 0))
```

---

## TODO

- [x] sfg_point
- [x] sfg_multipoint
- [x] sfg_linestring
- [x] sfg_multilinestring
- [x] sfg_polygon
- [x] sfg_multipolygon
- [x] sfg tests
- [x] sfc_point
- [x] sfc_multipoint
- [x] sfc_linestring
- [x] sfc_multilinestring
- [x] sfc_polygon
- [x] sfc_multipolygon
- [x] sfc m_range and z_range correctly reported
- [x] sfc tests
- [x] sf_point
- [x] sf_multipoint
- [x] sf_linestring
- [x] sf_multilinestring
- [x] sf_polygon
- [x] sf_multipolygon
- [x] sf tests
- [x] new `xyzm` argument in C++ functions doesn't break dependencies
- [x] C++ API - dimension correctly 'guessed'
- [x] `rcpp_to_sf()` api uses new xyzm argument
- [x] `sf_helper` functions
- [x] `sf_to_df()` needs to return `m` (not `z`) if dim == `XYM`

**Comment by mdsumner** [comment]
Ah, I see it: https://github.com/dcooley/sfheaders/blob/4f708f3ef560a5aaadb64d880ffec4113ca0f02b/inst/include/sfheaders/sfg/sfg_dimension.hpp#L19

It is valid, not a priority - but caught me out because I was expect z and m to be independent.

**Comment by dcooley** [comment]
yeah I wanted to re-write the `sfg_dimension()` bit to be more flexible with Z and M. Seems like a good enough reason to do this now you've found a case for it.

**Comment by dcooley** [comment]
https://github.com/dcooley/sfheaders/commit/9049d1d0e557d7194077ce62e1c7ff9ba35d52df has my current working solution 

```r
df <- data.frame(
  x = 1
  , y = 2
  , z = 3
)

sfg_point(
  obj = df
  , x = "x"
  , y = "y"
  , m = "z"
)

# [1] 1 2 3
# attr(,"class")
# [1] "XYM"   "POINT" "sfg" 
```

**Comment by SymbolixAU** [comment]
more examples

```r
df <- data.frame(
  ml_id = c(1,1,1,1,1,1,1,1,2,2,2,2,2)
  , l_id = c(1,1,1,2,2,3,3,3,1,1,1,2,2)
  , x = rnorm(13)
  , y = rnorm(13)
  , z = rnorm(13)
  , m = rnorm(13)
)

sfg_multipoint(
  obj = df, x = "x", y = "y", m = "m"
) %>% class
# [1] "XYM"        "MULTIPOINT" "sfg"

sfg_linestring(
  obj = df, x = "x", y = "y", m = "m"
) %>% class
# [1] "XYM"        "MULTIPOINT" "sfg"

sfg_multilinestring(
  obj = df, x = "x", y = "y", m = "m"
) %>% class
# [1] "XYM"        "MULTIPOINT" "sfg"

sfg_polygon(
  obj = df, x = "x", y = "y", m = "m"
) %>% class
# [1] "XYM"        "MULTIPOINT" "sfg"

sfg_multipolygon(
  obj = df, x = "x", y = "y", m = "m"
) %>% class
# [1] "XYM"        "MULTIPOINT" "sfg"
```

**Comment by SymbolixAU** [comment]
> but I'm wondering if there's a smarter way..

yeah I don't like what I've done, going to rethink it.

**Comment by mdsumner** [comment]
Certainly works though 👍👍

**Comment by dcooley** [comment]
ok I think I'm happier with this now. I've re-worked it. Need to write a few more tests and check dependencies, but I think it's better.

**Comment by SymbolixAU** [comment]
the `helper` functions need to be adapted to check which (if any) of the `z` and / or `m` columns exist, so it can infer the correct dimension.

**Comment by mdsumner** [comment]
Didn't I do that? (or something else)

**Comment by SymbolixAU** [comment]
Yes and No - you correctly check if `x` and `y` exist, but not `z` OR `m`.

In this exmaple, it would probably be expected the dimension is `XYM`, rather than `XYZ`.

```r
df <- data.frame(x=1, y=1, m=1)
 sf_point(df)
Simple feature collection with 1 feature and 0 fields
geometry type:  POINT
dimension:      XYZ
bbox:           xmin: 1 ymin: 1 xmax: 1 ymax: 1
z_range:        zmin: 1 zmax: 1
m_range:        mmin: NA mmax: NA
epsg (SRID):    NA
proj4string:    NA
         geometry
1 POINT Z (1 1 1)
```

**Comment by mdsumner** [comment]
I remember writing it to work, even though it couldn't at the time - I'll definitely go over this thoroughly, but  a bit lost in branches atm (ha!)

**Comment by SymbolixAU** [comment]
no it's ok, you're right, it _does_ work, I was checking the wrong thing.

**Comment by mdsumner** [comment]
cool no worries - btw sfheaders is my favourite package rn absolutely masssive step forward

**Comment by SymbolixAU** [comment]
It's been my most "fun" to build, along with `jsonify`, because there's clear logic every at every step and in every function, and the C++ code is written in such a way that any other package developer shouldn't have to care if their object is a data.frame, matrix, integermatrix, etc, the `sfheaders` namespace they use should "just work".

**Comment by SymbolixAU** [comment]
I've also been thinking about the "making sf modular" discussion I've seen around the place. If there's any desire from Edzar et al, `sfheaders` could be a dependency of `sf` to do all the to/from R work. But that's for another discussion.

**Comment by mdsumner** [comment]
I was going to bring that up! Since we are starting to have all the pieces - but I think it's unlikely to be feasible or much fun. My vague plan is to follow paleolimbot/geom (or learn enough from) to do more basic things (my workflows are full of this need) and simply demonstrate independence by crafting things that use just what they need. I have a ton of stuff with anglr and silicate to come, along these lines.

**Comment by SymbolixAU** [comment]
I may be doing paleolimbot a disservice, as I know it's still a new concept package, but I have to say I have a slight niggling issue with paleolimbot/geom. And any self proclaimed 'developer-focused' package which imports anything tidyverse (or **any** R package really) and uses imported R functions. 

In my mind, to be truly a developer-focused package you need to expose all the functionality through the compiled C/C++/Fortran code, **as well as** the R interface.

**Comment by SymbolixAU** [comment]
(and I don't want this to sound like a rant against tidyverse - I have huge respect for what they've done)

**Comment by SymbolixAU** [comment]
But I'm very keep to see where it (geom) goes and what it develops in to.

**Comment by mdsumner** [comment]
Well sure ... but gotta start somewhere. All I want as a basis really is sticky crs on bundled columns. Only the tidyverse has that atm, but not because it's the only way - it's basic facility that should be in base R. All the rest is grouping/nesting and lists. If there's a better basis I'm all ears!

**Comment by mdsumner** [comment]
I just wrote my own Todo! I'll be back about this headers stuff. Btw, vctrs is not the tidyverse it's a common basis for vectors reducing complexity and duplication anywhere in R. We don't all have write C

**Comment by SymbolixAU** [comment]
> diversity is good but hopefully patterns emerge

100% agree

**Comment by mdsumner** [comment]
This really helped focus my thoughts on this actually

**Comment by SymbolixAU** [comment]
I've just pushed a commit which I think finishes all my test-cases. Unless you have any other comments I'm happy to say this is done.

**Comment by mdsumner** [comment]
I'm all good, tried it out and don't see any problems. (Pretty fantastic power ...)

**Comment by dcooley** [comment]
And regarding the conversation about linking / developer libraries, I see you saw [my fork](https://github.com/paleolimbot/geom/issues/17#issuecomment-607031941) - this is how **I** would like it developed so that all the functions can be accessed through source code. This way the spatial ecosystem can be truely modular, while still keep the speed as the packages communicate with each other.

**Comment by mdsumner** [comment]
that's fab, I need to get up to speed with that level of coding
